export const ADD_COLUMN = 'ADD_COLUMN';
export const ADD_CARD = 'ADD_CARD';
export const UPDATE_SEARCHSTRING = 'UPDATE_SEARCHSTRING';
export const ADD_LIST = 'ADD_LIST';
export const TOGGLE_CARD_FAVORITE = 'TOGGLE_CARD_FAVORITE';